name: Python Flask CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pandas scikit-learn pytest pytest-cov

    - name: Jalankan Tests
      run: |
        # Robot akan mencari folder 'tests' di root proyek
        pytest --cov=processor --cov=app tests/